console.log(typeof'kavya')
console.log(typeof "gackagkjg")
console.log(typeof 1862639)
console.log(typeof -2378587219)
console.log(typeof true)
console.log(typeof false)
console.log(typeof'nsahcd')
console.log(typeof 234)
console.log(typeof'kavya')
console.log(typeof'kavya')